;             
CREATE USER IF NOT EXISTS "SA" SALT 'd7b4839734d91433' HASH 'b274fd651b77949d61a738fbe34dde9fe9a3fa657944bcaf9c4df8cb4ff0b56c' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_4F265111_6BF6_4AE7_9735_57044502E1E7" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0237988B_BB07_439A_A66E_B33AFA02C900" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1FD30BE6_CB45_4D92_BB41_532F016CFAD1" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_383BE95C_9C82_40F7_89A9_0889BBEA5B43" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_857D249B_57D4_46E2_9A86_93C2C6309E07" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2BF10773_31E2_4EDF_8823_72CCC85ED559" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EEB88578_3F2F_425A_9CB7_81A5C54A5470" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_05291C60_FE87_48BF_8D89_303738C9F874" START WITH 3 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."CAST"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_4F265111_6BF6_4AE7_9735_57044502E1E7" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_4F265111_6BF6_4AE7_9735_57044502E1E7",
    "CAST_ORDER" INTEGER NOT NULL,
    "CHARACTER" VARCHAR(255),
    "NAME" VARCHAR(255),
    "CREDIT_ID" BIGINT,
    "CAST_ID" BIGINT
);               
ALTER TABLE "PUBLIC"."CAST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAST;    
CREATE MEMORY TABLE "PUBLIC"."CREDIT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_2BF10773_31E2_4EDF_8823_72CCC85ED559" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2BF10773_31E2_4EDF_8823_72CCC85ED559"
);          
ALTER TABLE "PUBLIC"."CREDIT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CREDIT;  
CREATE MEMORY TABLE "PUBLIC"."CREW"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_383BE95C_9C82_40F7_89A9_0889BBEA5B43" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_383BE95C_9C82_40F7_89A9_0889BBEA5B43",
    "DEPARTMENT" VARCHAR(255),
    "JOB" VARCHAR(255),
    "NAME" VARCHAR(255),
    "CREDIT_ID" BIGINT,
    "CREW_ID" BIGINT
);         
ALTER TABLE "PUBLIC"."CREW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1F" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CREW;    
CREATE MEMORY TABLE "PUBLIC"."GENRE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_857D249B_57D4_46E2_9A86_93C2C6309E07" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_857D249B_57D4_46E2_9A86_93C2C6309E07",
    "NAME" VARCHAR(255),
    "TMDB_ID" BIGINT,
    "MOVIE_ID" BIGINT,
    "GENRE_ID" BIGINT
);          
ALTER TABLE "PUBLIC"."GENRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GENRE;   
CREATE MEMORY TABLE "PUBLIC"."MOVIE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_1FD30BE6_CB45_4D92_BB41_532F016CFAD1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1FD30BE6_CB45_4D92_BB41_532F016CFAD1",
    "BACKDROP_PATH" VARCHAR(255),
    "BUDGET" INTEGER NOT NULL,
    "HOMEPAGE" VARCHAR(255),
    "IS_ADULT" BOOLEAN NOT NULL,
    "ORIGINAL_LANGUAGE" VARCHAR(255),
    "ORIGINAL_TITLE" VARCHAR(255),
    "OVERVIEW" CLOB,
    "POPULARITY" FLOAT,
    "POSTER_PATH" VARCHAR(255),
    "RELEASE_DATE" VARCHAR(255),
    "REVENUE" INTEGER NOT NULL,
    "STATUS" VARCHAR(255),
    "TITLE" VARCHAR(255),
    "TMDB_ID" BIGINT,
    "VOTE_AVERAGE" FLOAT,
    "VOTE_COUNT" INTEGER NOT NULL,
    "CREDIT_ID" BIGINT NOT NULL
);           
ALTER TABLE "PUBLIC"."MOVIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_46" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MOVIE;   
CREATE MEMORY TABLE "PUBLIC"."PERSON"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_05291C60_FE87_48BF_8D89_303738C9F874" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_05291C60_FE87_48BF_8D89_303738C9F874",
    "BIOGRAPHY" CLOB,
    "BIRTHDAY" VARCHAR(255),
    "DEATHDAY" VARCHAR(255),
    "GENDER" INTEGER NOT NULL,
    "IMDB_ID" VARCHAR(255),
    "KNOWN_FOR_DEPARTMENT" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PLACE_OF_BIRTH" VARCHAR(255),
    "POPULARITY" FLOAT,
    "PROFILE_PATH" VARCHAR(255),
    "TMDB_ID" BIGINT
);
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;  
INSERT INTO "PUBLIC"."PERSON" VALUES
(2, STRINGDECODE('Thomas Jeffrey Hanks (born July 9, 1956) is an American actor and filmmaker. Known for both his comedic and dramatic roles, Hanks is one of the most popular and recognizable film stars worldwide, and is widely regarded as an American cultural icon.\n\nHanks made his breakthrough with leading roles in the comedies Splash (1984) and Big (1988). He won two consecutive Academy Awards for Best Actor for starring as a gay lawyer suffering from AIDS in Philadelphia (1993) and a young man with below-average IQ in Forrest Gump (1994). Hanks collaborated with film director Steven Spielberg on five films: Saving Private Ryan (1998), Catch Me If You Can (2002), The Terminal (2004), Bridge of Spies (2015), and The Post (2017), as well as the 2001 miniseries Band of Brothers, which launched him as a director, producer, and screenwriter.\n\nHanks'' other notable films include the romantic comedies Sleepless in Seattle (1993) and You''ve Got Mail (1998); the dramas Apollo 13 (1995), The Green Mile (1999), Cast Away (2000), Road to Perdition (2002), and Cloud Atlas (2012); and the biographical dramas Saving Mr. Banks (2013), Captain Phillips (2013), Sully (2016), and A Beautiful Day in the Neighborhood (2019). He has also appeared as the title character in the Robert Langdon film series, and has voiced Sheriff Woody in the Toy Story film series.\n\nDescription above from the Wikipedia article Tom Hanks, licensed under CC-BY-SA, full list of contributors on Wikipedia.'), '1956-07-09', NULL, 2, 'nm0000158', 'Acting', 'Tom Hanks', 'Concord, California, United States', 36.0369987487793, '/xndWFsBlClOJFRdhSt4NBwiPq2o.jpg', 31);     
CREATE MEMORY TABLE "PUBLIC"."PRODUCTION_COMPANY"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_EEB88578_3F2F_425A_9CB7_81A5C54A5470" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EEB88578_3F2F_425A_9CB7_81A5C54A5470",
    "LOGO_PATH" VARCHAR(255),
    "NAME" VARCHAR(255),
    "ORIGIN_COUNTRY" VARCHAR(255)
); 
ALTER TABLE "PUBLIC"."PRODUCTION_COMPANY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCTION_COMPANY;      
CREATE MEMORY TABLE "PUBLIC"."PRODUCTION_COUNTRY"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_0237988B_BB07_439A_A66E_B33AFA02C900" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0237988B_BB07_439A_A66E_B33AFA02C900",
    "ISO_3166_1" VARCHAR(255),
    "NAME" VARCHAR(255),
    "MOVIE_ID" BIGINT
);            
ALTER TABLE "PUBLIC"."PRODUCTION_COUNTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A4" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCTION_COUNTRY;      
ALTER TABLE "PUBLIC"."GENRE" ADD CONSTRAINT "PUBLIC"."FKESY45NVXOT9JYISCT4O3S3L3L" FOREIGN KEY("MOVIE_ID") REFERENCES "PUBLIC"."MOVIE"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."CAST" ADD CONSTRAINT "PUBLIC"."FKPC3ETV9C6PNUXI7XLDA77N92L" FOREIGN KEY("CREDIT_ID") REFERENCES "PUBLIC"."CREDIT"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."CREW" ADD CONSTRAINT "PUBLIC"."FKTP477N56M15GBA6EQSSC2RP99" FOREIGN KEY("CREW_ID") REFERENCES "PUBLIC"."CREDIT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."CAST" ADD CONSTRAINT "PUBLIC"."FKCDESD1UNNPAVM3M1N6HHJV0O2" FOREIGN KEY("CAST_ID") REFERENCES "PUBLIC"."CREDIT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."MOVIE" ADD CONSTRAINT "PUBLIC"."FKTN0XHSD5DKY8XWUPVIFI7PUEP" FOREIGN KEY("CREDIT_ID") REFERENCES "PUBLIC"."CREDIT"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."PRODUCTION_COUNTRY" ADD CONSTRAINT "PUBLIC"."FK4OMBVL2COFL5JP52CJN8C9FO2" FOREIGN KEY("MOVIE_ID") REFERENCES "PUBLIC"."MOVIE"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."CREW" ADD CONSTRAINT "PUBLIC"."FKQU5I0LDMXPBIT0BUPSGYRCOSF" FOREIGN KEY("CREDIT_ID") REFERENCES "PUBLIC"."CREDIT"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."GENRE" ADD CONSTRAINT "PUBLIC"."FKPS59ITWDVQYGJVJRIJGSLHLL4" FOREIGN KEY("GENRE_ID") REFERENCES "PUBLIC"."MOVIE"("ID") NOCHECK;         
